### ISSUE TITLE
Current file is not taken into quota consideration

### ISSUE THREAD

**Issue by sergiz** [drakkan/sftpgo#128] opened 2020-06-16 04:58 UTC
Hello.

I think I have found a bug with quotas.

I have a user for whom I set 12MB quota (12582912 bytes). Let's say I then upload a few small files, so 8MB is used (meaning 4 MB are still free). I can then upload a file of any size (like 30MB) and it will succeed. If I check my dataprovider, "used_quota_size" will be higher than "quota_size". Only after If I want to upload another file, it will be denied due to quota exceeded.

I'm using the currently latest version (commit c491133aff4499cc48ec79a64ed53c09b77ec421).

**Comment by drakkan** [comment] 2020-06-16 20:53
Hi,

this works as intended. I agree that this feature can be improved and we can check the current uploaded size against the remaining size calculated when the upload starts.

**Comment by sergiz** [comment] 2020-06-17 00:39
But doesn’t it make quota useless then? Anyone who has 1 byte of quota left can come and upload 1TB file.

**Comment by drakkan** [comment] 2020-06-17 03:03
> But doesn’t it make quota useless then? Anyone who has 1 byte of quota left can come and upload 1TB file.

I agree that this could be an issue with low quota limits and it will be fixed

**Closed** 2020-06-18 20:38 UTC
Labels: enhancement
