### ISSUE TITLE
Different GUI Languages

### ISSUE THREAD

**Issue by Binary-System** [drakkan/sftpgo#1273] opened 2023-04-28 11:03 UTC
Is there a way to switch GUI languages that I don't see? 
I can contribute translated template files (german) but I see no way to make them user/admin selectable except of hard configuring them in the yaml file.

Translation files would be the more nicer way to do it but not enough GO experience for that right now

**Comment by drakkan** [comment] 2023-04-28 12:02
It is not currently supported. Duplicate of #924 #949

**Closed by drakkan** 2023-04-28 12:02 UTC

**Comment by gedw99** [comment] 2023-05-12 17:20
This can easily be done by using go template with google translate api.

the translations are perfect imho

**Comment by drakkan** [comment] 2023-05-12 17:32
> This can easily be done by using go template with google translate api.
> 
> the translations are perfect imho

yes, but we need to support translations in both the templates and the backend. This is doable but requires time and continuous maintenance. See the related issues. Thank you
