### ISSUE TITLE
[Question]: Is there anyway to check which specific ciphers, host_key_algorithms, kex_algorithms, macs are used for a currently sftp connected client in the logs?

### ISSUE THREAD

**Issue by jerrywoo96** [drakkan/sftpgo#1416] opened 2023-09-13 01:57 UTC
### Is your feature request related to a problem? Please describe.

Is there any way to check which specific ciphers, host_key_algorithms, kex_algorithms, macs are used for a currently connected sftp client in the logs? I would like to only enable the highest supported security settings in the config file, such that i do not have to trial and error disable each option 1 by 1 until my client fails to connect.

### Describe the solution you'd like

show specific ciphers, host_key_algorithms, kex_algorithms, macs used for a currently connected sftp client in the log.

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment] 2023-09-13 10:09
This looks like a duplicate of #1324

**Closed by drakkan** 2023-09-13 10:09 UTC
Labels: suggestion
