### ISSUE TITLE
Docker SFTPGo - 2.0.1 uncorrectly read /etc/sftpgo/httpauth

### ISSUE THREAD

**Issue by skoriy88** [drakkan/sftpgo#310] opened 2021-02-10 21:31 UTC
When using /etc/sftpgo/httpauth mounted to docker image and user/password created by sudo htpasswd -B -c /etc/sftpgo/httpauth sftpgoweb, during login to web admin receive error "not found: sql: no rows in result set"

SFTPGo - 2.0.1

**Comment by drakkan** [comment] 2021-02-11 06:50
Hi,

this seems a duplicate of #306 `httpauth` for web admin is gone, please login using the default user ("admin"/"password") and create other administrators from the web admin interface.

httpauth is now supported only for the telemetry server. Please let me know if I forgot to update the docs somewhere, thank you

**Comment by skoriy88** [comment] 2021-02-11 07:05
Oh, thanks! 
So is there any way to set up web admin password without first login? Maybe I can use some script or etc? 
I use the sftpgo docker in my infra and previous it was a very nice possibility to set up an admin password during infrastructure deployment. 
Thanks a lot for your great job!

**Comment by drakkan** [comment] 2021-02-11 07:39
Hi,

if you are using the memory provider you can include your admins inside the dump, for example:

```
{"users":[],"folders":[],"admins":[{"id":1,"status":1,"username":"admin","password":"$argon2id$v=19$m=65536,t=1,p=2$cV3kU/yC9jmdLOxOFdsc2Q$J+n24soAOcYBrlH8w7q7sSdJKNJ8efCuM+x5gnSuO+I","email":"","permissions":["*"],"filters":{}}],"version":6}
```

for any other provider you can use the `--loaddata-from` serve option but you need to update to [this commit](https://github.com/drakkan/sftpgo/commit/4ddfe41f23a09a1a22a79b99bdc0c5a0895cfbc2), admins were ignored before, sorry

**Comment by skoriy88** [comment] 2021-02-11 11:49
Thanks for your support!

**Closed** 2021-02-11 11:49 UTC
