### ISSUE TITLE
Need fix 

### ISSUE THREAD

**Issue by Justsenger** [drakkan/sftpgo#998] opened 2022-09-25 16:30 UTC
When I try to download some files from the share it gives an error,in the console:

Uncaught TypeError: Cannot read properties of null (reading 'split')
    at getNameFromMeta (browse:380:21)
    at B.action (browse:490:37)
    at t (dataTables.buttons.min.js:50:58)
    at HTMLButtonElement.<anonymous> (dataTables.buttons.min.js:50:537)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)

This seems to mean that the checkbox is not configured correctly,  when i added "console.log(meta);“ into function getNameFromMeta(meta),it always show me "null".

**Comment by drakkan** [comment] 2022-09-25 17:29
I cannot reproduce and you have not provided any information to reproduce the reported issue.
Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Closed by drakkan** 2022-09-25 17:29 UTC

**Comment by Justsenger** [comment] 2022-09-26 03:17
Step: Create a share with a directory, put some files in the directory.
1.Select some files and download zip, then nothing happens.
2.When a file is selected, it will show that all files are selected.

**Comment by drakkan** [comment] 2022-09-26 07:38
Are you sure you are using SFTPGo from this repo? (I can see similar errors in your fork). As you can see from the following screencast, it works fine for me

[Video del 26-09-2022 09:34:08.webm](https://user-images.githubusercontent.com/553263/192219724-c8c9f957-548e-41cc-b80a-bed7b3e07392.webm)

**Comment by Justsenger** [comment] 2022-09-26 08:28
I'm sorry it was my mistake, I just installed version 2.3.5 and simply overwritten the webclient folder of the repository with the original, this is why the error occurs.
In addition, I am making the corresponding Chinese user interface, this is my first time making a project on Github, do you have any good ideas for me?

**Comment by Justsenger** [comment] 2022-09-26 12:09
I agree with you that this is indeed a promising and long-term thing. I'm looking forward to your team getting it done sooner rather than later. :)
