### ISSUE TITLE
invalid credential with default configuration. Hosted on GCP Debian VM

### ISSUE THREAD

**Issue by tan-vo-cityblock** [drakkan/sftpgo#515] opened 2021-08-27 18:56 UTC
Hi there,

I setup sftpgo using the default configuration on Google Cloud Debian VM.  Then I setup an admin account on the web interface.  I can see the username in: /var/lib/sftpgo/sftpgo.db. When I log into the web interface using the web interface after rebooting the VM, it gives me the "invalid credentials" error. I double checked the login I typed in. I could also see my username in the database. What did I go wrong here? Thank you for your help.

**Comment by ZyanKLee** [comment] 2021-08-31 09:27
I encountered the same issue with a password of 64 characters. I could create the admin user, but login was not possible. Next I tried it with 32 characters, which works now.

**Comment by drakkan** [comment] 2021-08-31 09:51
This could be related to bcrypt passwords length (but I'm unable to reproduce locally), can you please try using argon2? Argon2 should not have a max password length. Thank you

**Comment by ZyanKLee** [comment] 2021-08-31 10:00
perhaps this might also be a storage provider problem? I'm using sqlite currently. When the field is limited to <64 chars and inserted values are silently cut, this could happen.

**Comment by ZyanKLee** [comment] 2021-08-31 10:13
Ok, this is odd and a little embarassing: I removed the docker container and the sqlite database, started with argon2id, tested it (works!), removed the container and the db file again, started without argon2id and re-tested and it still works.
So whatever the issue was for me: I cannot reproduce it anymore.
Sorry for bothering you.

**Comment by drakkan** [comment] 2021-08-31 10:17
This is strange, another user reported the same issue in the past but I'm unable to reproduce it. I just tested using a 115 chars password and it works. At the dataprovider level we have this: `"password" varchar(255) NOT NULL`, so until 255 chars we should be fine. If you are able to reproduce again please report the exact steps, thank you

**Comment by drakkan** [comment] 2021-08-31 10:29
I think the issue is [here](https://github.com/drakkan/sftpgo/blob/main/templates/webadmin/adminsetup.html#L102), as you can see there is `maxlength="60"` for user and password in the initial setup screen. I'm working on a big refactor to add builtin TOTP support (and I'll already changed this template), I'll include this fix in the next commit

**Comment by drakkan** [comment] 2021-09-04 10:16
This is now fixed both in the development branch and in 2.1.x. The fix will be included in 2.1.1 release

**Closed by drakkan** 2021-09-04 10:16 UTC
