### ISSUE TITLE
sftpgo 2.4.4 ignores log level setting

### ISSUE THREAD

**Issue by pzbitskiy** [drakkan/sftpgo#1199] opened 2023-02-20 18:12 UTC
sftpgo  v2.4.4 (`sftpgo_2.4.4-1_arm64.deb`) installed as a service completely ignores log level setting.

What tried:
1. Environment variable
```
cat /etc/sftpgo/env.d/log.env
SFTPGO_LOG_LEVEL=error
```
2. command line option
```
cat /etc/systemd/system/multi-user.target.wants/sftpgo.service | grep ExecStart
ExecStart=/usr/bin/sftpgo serve --log-level=error
```

The log file still has debug and info messages:
```
Feb 20 12:18:41 localhost.localdomain sftpgo[53729]: {"level":"debug","time":"2023-02-20T12:18:41.912","sender":"webdavd","message":"configured TLS..."}
```

2.4 branch has all new logLevel code but for whatever reason it does not work.

**Comment by drakkan** [comment] 2023-02-20 18:19
> sftpgo v2.4.4 (`sftpgo_2.4.4-1_arm64.deb`) installed as a service completely ignores log level setting.
> 
> What tried:
> 
> 1. Environment variable
> 
> ```
> cat /etc/sftpgo/env.d/log.env
> SFTPGO_LOG_LEVEL=error
> ```
> 

that's wrong, env vars for command flags must be set before starting SFTPGo, env files are read once the logger is already initialized
> 2. command line option
> 
> ```
> cat /etc/systemd/system/multi-user.target.wants/sftpgo.service | grep ExecStart
> ExecStart=/usr/bin/sftpgo serve --log-level=error
> ```
> 

I cannot reproduce, this works for me

> The log file still has debug and info messages:
> 
> ```
> Feb 20 12:18:41 localhost.localdomain sftpgo[53729]: {"level":"debug","time":"2023-02-20T12:18:41.912","sender":"webdavd","message":"configured TLS..."}
> ```
> 
> 2.4 branch has all new logLevel code but for whatever reason it does not work.

closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Closed by drakkan** 2023-02-20 18:19 UTC

**Comment by pzbitskiy** [comment] 2023-02-20 18:25
> that's wrong, env vars for command flags must be set before starting SFTPGo, env files are read once the logger is already initialized

I understand how it works but I guess this behavior should be documented.

> I cannot reproduce, this works for me

Indeed, it started working after reboot, it appears systemd did not pick up the change. Thank you.

**Comment by drakkan** [comment] 2023-02-20 18:45
> > that's wrong, env vars for command flags must be set before starting SFTPGo, env files are read once the logger is already initialized
> 
> I understand how it works but I guess this behavior should be documented.
> 

it is documented

> > I cannot reproduce, this works for me
> 
> Indeed, it started working after reboot, it appears systemd did not pick up the change. Thank you.

so you don't even read the systemd documentation

**Comment by pzbitskiy** [comment] 2023-02-20 19:31
> so you don't even read the systemd documentation

educate me, which part? What else needed in addition to `systemctl daemon-reload && systemctl restart  sftpgo`?
