### ISSUE TITLE
Webdav as storage backend?

### ISSUE THREAD

**Issue by w3bstate** [drakkan/sftpgo#1122] opened 2022-12-28 16:27 UTC
Hello.

Thanks for your time and effort on creating such a useful software!

I wonder if it's currently possible to use webdav protocol for the storage backend?

Or I have to create it by my own using Fs interface?

Thank you kindly for your answer.

**Comment by drakkan** [comment] 2022-12-28 16:31
Duplicate of #796

**Closed by drakkan** 2022-12-28 16:31 UTC
