### ISSUE TITLE
Groups with trailing space in the name

### ISSUE THREAD

**Issue by ward-74** [drakkan/sftpgo#1181] opened 2023-02-07 21:01 UTC
Prevent groups from having a trailing space on the name when created. 

Since I did that, I cannot delete the group. I figured out how to edit the group by adding the space in the URL.

I have not found a work-around to delete the group.

**Comment by drakkan** [comment] 2023-02-08 08:50
Duplicate of #1119

**Closed** 2023-02-08 08:50 UTC
