### ISSUE TITLE
unable to compile from sources

### ISSUE THREAD

**Issue by WalkerDaleT** [drakkan/sftpgo#107] opened 2020-04-09 20:45 UTC
Receiving the following error on ubuntu 18.04 when trying to compile with sample build command
Looks like import is broken.
/dataprovider/dataprovider.go:45:2: code in directory /home/dale/source/src/github.com/nathanaelle/password expects import "github.com/nathanaelle/password/v2"

**Comment by drakkan** [comment] 2020-04-09 21:49
This seems a duplicate of #97. It is fixed in this commit https://github.com/drakkan/sftpgo/commit/f55851bdc81935d1e602cd43dda930ae02766b45

So if you want to build from source an old version you have to apply that patch.

Unluckly `nathanaelle/password` was updated to use go modules breaking backward compatibility

**Closed by drakkan** 2020-04-09 21:49 UTC

**Comment by drakkan** [comment] 2020-04-10 07:32
Another way to rebuild 0.9.6 from source is to download the source with deps from [here](https://github.com/drakkan/sftpgo/releases/download/0.9.6/sftpgo_0.9.6_src_with_deps.tar.xz) and to build in vendoring mode, for example:

```
go build -mod=vendor -i -ldflags "-s -w -X github.com/drakkan/sftpgo/utils.commit=`git describe --always --dirty` -X github.com/drakkan/sftpgo/utils.date=`date -u +%FT%TZ`" -o sftpgo
```

this way the old `nathanaelle/password` module included inside the vendor dir should be used
