### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by Knkkyl** [drakkan/sftpgo#1403] opened 2023-08-29 12:54 UTC
Hello,

we're using SFTPGo for transfer of (very) large files. It would be really useful if there was some kin of progress indicator during upload, ideally with a list of files currently being uploaded and how far they got. Could you implement something like this?

Thanks

_Originally posted by @blindmikesghost in https://github.com/drakkan/sftpgo/discussions/1352_

**Comment by drakkan** [comment] 2023-08-29 13:04
Duplicate of #1352

**Closed by drakkan** 2023-08-29 13:04 UTC

**Comment by drakkan** [comment] 2023-08-29 13:07
Please check our support policy, we prioritize requests from project sponsors/support plan subscribers sorry
