### ISSUE TITLE
Can't change directory: "<dir-name>" is not a directory when using Idrive E2

### ISSUE THREAD

**Issue by mezuky04** [drakkan/sftpgo#1097] opened 2022-12-11 20:44 UTC
Hello. I'm using SFTPGo with Idrive E2 and there seems to be a problem with empty directories. 

If an empty directory is created via the Idrive E2 dashboard or any S3 client and I try to `cd` into the new directory, the error `Can't change directory: "<dir-name>" is not a directory` is returned.

```shell
# The directory my-dir was created from the Idrive E2 dashboard
sftp> cd my-dir
Can't change directory: "/my-dir" is not a directory
```
If the directory is created with the `mkdir` command, everything works as expected.
```shell
sftp> mkdir my-dir
sftp> cd my-dir
sftp> pwd
Remote working directory: /my-dir
```

I tested with different S3-based storage providers and the problem only happens with Idrive E2. I can give you a test Idrive E2 account in case you need it to replicate the problem 🙂

**Comment by drakkan** [comment] 2022-12-12 11:25
Hello,

S3 has no folder, you create a key with a particular mimetype or suffix. If the "folder" created by the dashboard is not recognized as a folder in the directory listing, there is nothing we can do in SFTPGo, if the problem is with stat calls we can fix.

Many times in the past I have connected to various test accounts to verify and in most cases people disappear as soon as I fix the problem, often I don't even get a thank you. The last experience like this is this [one](https://github.com/drakkan/sftpgo/issues/776#issuecomment-1325703034). 

So I learned the lesson the hard way, if you want me to check what's going on at least a bronze sponsorship is required, sorry.

Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by mezuky04** [comment] 2022-12-12 11:48
Thanks for the reply. I'm using SFTPGo for personal use and sponsoring 100$ each month would be too much at the current moment. I'm trying different things with SFTPGo because I want to use it at the company I work and if in the end it will work for the needed use cases as expected, I will make sure the company will sponsor the project.

Right now I'm sponsoring the project from my personal account and I can make a one-time payment for this issue. What amount would cover your time to check the problem?

**Comment by drakkan** [comment] 2022-12-12 14:21
> Thanks for the reply. I'm using SFTPGo for personal use and sponsoring 100$ each month would be too much at the current moment. I'm trying different things with SFTPGo because I want to use it at the company I work and if in the end it will work for the needed use cases as expected, I will make sure the company will sponsor the project.
> 

Ok, so let's wait for your company to sponsor the project, this S3 compatible storage provider will be supported in some way

> Right now I'm sponsoring the project from my personal account and I can make a one-time payment for this issue. What amount would cover your time to check the problem?

**Comment by mezuky04** [comment] 2022-12-12 14:35
Done 🙂

**Closed** 2022-12-13 07:55 UTC

**Comment by mezuky04** [comment] 2022-12-15 19:43
Thank you for fixing the problem 🙂

**Comment by drakkan** [comment] 2022-12-16 08:31
> Thank you for fixing the problem slightly_smiling_face

I help people who help the project. This change will be part of the 2.4.3 release expected in approximately 2 weeks
