### ISSUE TITLE
Webdav error 0x80070021

### ISSUE THREAD

**Issue by bylli79** [drakkan/sftpgo#481] opened 2021-07-19 12:31 UTC
Hello,
i have recently installed sftpgo in doker.
From window when I try to copy via webdav, I get error 0x80070021.

What can I do?

**Comment by drakkan** [comment] 2021-07-19 12:46
Hi,

from a quick google search i found that this windows error should mean "permission denied". If you can confirm a permission issue by reading the SFTPGo logs (in future please post SFTPGo logs and not windows errors) you likely have to configure docker appropriately, please take a look [here](https://github.com/drakkan/sftpgo/tree/main/docker#running-as-an-arbitrary-user) or, event better, to the official docker docs.

**Comment by bylli79** [comment] 2021-07-21 14:23
Sorry for my English.
I started docker with --user passing it as the UID / GID parameter of the data mounted folder.
The problem persists.
From the logs I find the following error:
connection removed, close fs error: <nil>, num open connections: 0
The problem occurs when I copy a group of files and folders together.
At the occurrence of the error, if I click on "retry" of each file that gave this error, the file is copied.
Could it be a lock problem with the file you are copying?

**Comment by drakkan** [comment] 2021-07-21 14:37
Please post the full logs, not only the last line.

A similar problem was fixed a while ago, see #239, is this the same or a similar error? Please also take a look there to understand how to report something that allows me to reproduce the issue.  

Can you please share the sftpgo version you are using, the client version etc.? Do you have issue also if you connect via SFTP, using the same user, instead of WebDAV? Thank you

**Comment by drakkan** [comment] 2021-07-21 15:35
Maybe these patches could help

https://github.com/golang/net/pull/92
https://github.com/golang/net/pull/93

anyway before merging them I must be able to reproduce the issue. I just tested from windows 10 (in the logs the client is `Microsoft-WebDAV-MiniRedir/10.0.19041`) and I have no issues. Please help me to better understand the issue, thank you

**Comment by bylli79** [comment] 2021-07-21 15:40
Sure.
Restarting the docker I lost the old logs.
We are doing tests with my systems engineer.
This way I can give you all the information.

Thank you

**Comment by drakkan** [comment] 2021-07-25 08:08
Hi,

I added some new test cases and fixed them by adding some patches to our `net/webdav` fork, please take a look at this [commit](https://github.com/drakkan/sftpgo/commit/a7313e4492d95b994a5ee2d2ed824c69ca39e95c) for more details.

WebDAV clients can, optionally, lock a resource and Windows WebDAV client uses locks. 

The above patch fix, for example, the following case:

```
/LOCK file.txt
/DELETE file.txt
/LOCK file.txt
```

the latest LOCK request failed before this patch because the webdav library didn't release the lock for deleted resources. This is and some other similar cases are now fixed.

Can you please test again using the latest `edge` docker image? Please post also the SFTPGo version, so I can double check that you are using the right docker image.

If the issue persists, I need the client request sequence for the problematic case to be able to reproduce and fix the problem. Full SFTPGo logs (indicating the problematic file name) and/or a network dump will help.

Please note that if multiple clients are locking the same resource the reported error is expected. Thank you

**Comment by drakkan** [comment] 2021-09-11 15:44
The above fixes are now included in v2.1.2, please reopen providing the info to understand/reproduce the issue if it still happens, thanks

**Closed by drakkan** 2021-09-11 15:44 UTC
