### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by yiuqinze** [drakkan/sftpgo#1743] opened 2024-09-04 10:09 UTC
### Is your feature request related to a problem? Please describe.

Is there any plan to support simplified Chinese?

### Describe the solution you'd like

Hope to support Simplified Chinese

### What are you using SFTPGo for?

Medium business

**Comment by drakkan** [comment] 2024-09-04 13:08
Hello, we have received a Chinese translation but we are unable to review it ourselves.

Translating phrases is hard, even lexically correct translations in the wrong context can completely change the meaning and confuse users. Also, this is an ongoing effort, translations will be added, removed, updated in every release, even minor ones.

We need to hire a professional translator to review the Chinese translation and make sure it meets the quality requirements. This can only happen if some Chinese companies are interested enough to support the project financially and this is not the case so far. Sorry

**Comment by alexitx** [comment] 2024-11-03 01:10
Hi, I really appreciate you upholding high standards for quality translations. Would it be possible to support manually adding user-provided translations independent of the official ones if it's feasible? I would like to translate the UI for myself in the meantime. I see the strings are stored in `static/locales/<lang>`, but there are more changes required in the templates and vendor scripts.

**Comment by ralhako** [comment] 2024-12-13 14:52
Hello alexitx, that's a good suggestion.
Hello drakkan, maybe that's feasible?

**Comment by drakkan** [comment] 2024-12-14 11:52
duplicate of #1569

**Closed** 2024-12-14 11:53 UTC
Labels: suggestion

**Comment by ralhako** [comment] 2024-12-17 16:52
@alexitx translate it here: [Crowdin](https://crowdin.com/project/sftpgo/fr)! Download translate.json and overrite the file in /usr/share/sftpgo/static/locales/en und ../it. That works for yourself in the meantime 😉
