### ISSUE TITLE
Language enhancement

### ISSUE THREAD

**Issue by yaboso** [drakkan/sftpgo#1413] opened 2023-09-07 14:52 UTC
### Is your feature request related to a problem? Please describe.

Hello,

I noticed that sftpgo unfortunately only offers English as a language. This is okay for most people, but a language extension would be helpful in quite a few cases and would also increase the reach and attention of sftpgo.

### Describe the solution you'd like

If possible, I would offer to do the translation of the language German completely. That would be small contribution.

Thank you.

**Comment by drakkan** [comment] 2023-09-07 15:04
duplicate of #949 #924

There are two other open questions that require the same feature, unfortunately no company seems interested enough to sponsor this work.

We need to add a translation framework that also allows strings coming from the backend to be translated, translating strings in templates is not enough, try to edit directly the templates and see the result.

Reviewing the translations before merging them is also a lot of work, e.g. we have to check each string using an online translator to make sure it does not contain offensive words

**Closed by drakkan** 2023-09-07 15:04 UTC
Labels: duplicate, suggestion
